/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_reacttest_HelloWorld */

#ifndef _Included_com_example_reacttest_HelloWorld
#define _Included_com_example_reacttest_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_reacttest_HelloWorld
 * Method:    displayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_reacttest_HelloWorld_displayHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
